# start at 1
set -g base-index 1

# something to make clipboard work
set-option -g default-command "/opt/local/bin/reattach-to-user-namespace bash"

# don't wait for timeout
set -s escape-time 0

# ctrl-b is too useful
unbind C-b
set -g prefix C-Space

# get rid of ugly hostname, etc.
set -g status-right ''

# aesthetics
set -g status-bg default
set -g status-fg default

# scrolling but not on OSX?
# set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# enable mouse things
# set-option -g mouse-select-pane on
# set-option -g mouse-select-window on
# set-window-option -g mode-mouse on
