set -g base-index 1
set-option -g default-command "/opt/local/bin/reattach-to-user-namespace bash"
set -s escape-time 0

unbind C-b
set -g prefix C-Space

set -g status-bg blue
set -g status-fg white

